name: 🐧 Linux
on:
  push:
    paths: [godot_remote/**, .github/**, '!.github/**/util_*', '**.patch', SConstruct]
  pull_request:
    types: [opened, edited]
  repository_dispatch:

# Stop the same workflow actions
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  linux-gdnative:
    name: Linux GDNative ${{ matrix.name }}
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x64
            bits: 64

          - name: x86
            bits: 32

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Compile GDNative 
        uses: ./.github/actions/compile_module
        with:
          is_module: no
          platform: linux
          target: release
          bits: bits=${{ matrix.bits }}
          artifact: linux

      #- name: Upload OpenH264
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: linux
      #    retention-days: 7
      #    path: godot_remote/openh264/libopenh264-2.2.0-linux${{ matrix.bits }}.6.so


  linux-module:
    name: Module x64
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Godot
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          ref: 3.4.4-stable
          lfs: true
          submodules: recursive

      - name: Checkout GodotRemote
        uses: actions/checkout@v3
        with:
          path: gr
          lfs: true
          submodules: recursive

      - name: Compile Module 
        uses: ./gr/.github/actions/compile_module
        with:
          is_module: yes
          target: release_debug
          tools: yes
          platform: x11
          bits: bits=64
          artifact: linux_editor
