name: 2. ↗️ Update GDNative binaries from collected artifacts

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  update:
    name: Update GDNative binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      
      - name: Remove previous libs
        run: rm -rf addons/godot_remote/libs

      - name: Download Windows Binaries
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: util_collect_binaries.yml
          name: gdnative_libs
          path: .

      - name: Commit report
        run: |
          git config --global user.name 'Auto Updater'
          git config --global user.email 'auto-updater@users.noreply.github.com'
          git add -A
          git commit -am "[CI] ↗️ Updated Addon"
          git push