name: ↗️ Update binaries from artifacts

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      
      - name: Download Windows Binaries
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: windows_builds.yml
          path: extracted_files
      
      - name: Download Linux Binaries
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: linux_builds.yml
          path: extracted_files
      
      - name: Download MacOS Binaries
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: macos_builds.yml
          path: extracted_files

      # To combine mac binaries:
      # lipo -create bin/godot.osx.tools.x86_64 bin/godot.osx.tools.arm64 -output bin/godot.osx.tools.universal
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gdnative
          retention-days: 7
          path: extracted_files/*
