name: 🪟 Windows
on:
  push:
    paths: [godot_remote/**, .github/**, '!.github/**/util_*', '**.patch', SConstruct]
  pull_request:
    types: [opened, edited]
  repository_dispatch:

# Stop the same workflow actions
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  windows-gdnative:
    name: Windows GDNative ${{ matrix.name }}
    runs-on: "windows-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x64
            bits: 64

          - name: x86
            bits: 32

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Compile GDNative 
        uses: ./.github/actions/compile_module
        with:
          is_module: no
          platform: windows
          target: release
          bits: bits=${{ matrix.bits }}
          artifact: win
  
  
  windows-module:
    name: Module ${{ matrix.name }}
    runs-on: "windows-latest"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x64
            bits: 64

          - name: x86
            bits: 32

    steps:
      - name: Checkout Godot
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          ref: 3.4.4-stable
          lfs: true
          submodules: recursive

      - name: Checkout GodotRemote
        uses: actions/checkout@v3
        with:
          path: gr
          lfs: true
          submodules: recursive

      - name: Compile Module
        uses: ./gr/.github/actions/compile_module
        with:
          is_module: yes
          target: release_debug
          tools: yes
          platform: windows
          bits: bits=${{ matrix.bits }}
          artifact: win_editor
